spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource: # 配置数据源
    # 说明：如果没有指定useSSL=true，启动项目可能会爆红警告
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hsp
    driver-class-name: com.mysql.jdbc.Driver
    druid:  # 配置Druid
      stat-view-servlet:  # 启用监控功能
        enabled: true
        login-username: jack
        login-password: 123
        reset-enable: false
      web-stat-filter:    # 配置web监控
        enabled: true
        url-pattern: /*   # 过滤所有请求，exclusions表示排除的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:     # sql监控
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:     # 配置sql防火墙
          enabled: true
          config:
            drop-table-allow: false # 不允许删除行
            select-all-column-allow: false  # 不允许查询所有字段的 select * from `xx`
#server:  # 服务器配置
#  # 配置端口
#  port: 8080
#  tomcat: # 对Tomcat进行配置
#    threads:
#      max: 10 # 最大的工作线程，默认是200
#      min-spare: 5 # 最小工作线程，默认是10
#    accept-count: 200 # tomcat启动的线程达到最大值，接受排队的请求个数，默认是100
#    max-connections: 2000 # 最大连接数，并发数
#    connection-timeout: 10000 # 建立连接的超时时间，单位是毫秒
