spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#server:  # 服务器配置
#  # 配置端口
#  port: 8080
#  tomcat: # 对Tomcat进行配置
#    threads:
#      max: 10 # 最大的工作线程，默认是200
#      min-spare: 5 # 最小工作线程，默认是10
#    accept-count: 200 # tomcat启动的线程达到最大值，接受排队的请求个数，默认是100
#    max-connections: 2000 # 最大连接数，并发数
#    connection-timeout: 10000 # 建立连接的超时时间，单位是毫秒
