spring:
  mvc:
    static-path-pattern: /charlieRes/**   # 修改静态资源访问的路径/前缀
    hiddenmethod:
      filter:
        enabled: true   # 启用了HiddenHttpMethodFilter，支持页面表单请求Rest风格url
    view:               # 配置视图解析器
      suffix: .html     # 后缀名
      prefix: /charlieRes/  # 前缀名：需要根据配置的静态资源路径前缀进行调整。如果没配置，则使用/
    contentnegotiation:
      favor-parameter: true # 开启基于请求参数的内容协商功能
      parameter-name: charlieFormat # 指定一个内容协商的参数名

  # 小技巧：在最高级(前面没空格)输入根属性(static-locations)
  web:
    resources:
      static-locations:   # private String[] staticLocations;
        # 修改/指定静态资源访问的路径/位置
        - "classpath:/charlie/"
        # 添加新路径/位置后，原来位置被破坏。如果需要，仍需要进行指定
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"